### ISSUE TITLE
Documentation Typos

### ISSUE THREAD

**Issue by szipper** [geotopmodel/geotop#13]
I noticed a couple typos in the documentation and wanted to point them out here.

Table 12.1.1: Range for LSAI listed as {0,1} but LSAI > 1 is possible
Table 16.1: default value for SurFlowResExp is outside of defined range

**Comment by XiaoqingPeng** [comment]
Hi All,
  I am new for running GEOtop model. I can not find the associated document stating "io_it.ini" file. Simultaneous, there are some errors for running test case. Where can I find the help, such as forum or others. Thanks!
Peng

**Comment by szipper** [comment]
Hi Peng-
This website has a link to the Users Manual and a mailing list: http://geotopmodel.github.io/geotop/
The mailing list is a Google Group so you can look at old posts to help answer your questions, or send an email out yourself.

The io_it.ini file is input for the MeteoIO library which preprocesses meteorological data. More info here: https://models.slf.ch/p/meteoio/

**Comment by ecor** [comment]
Here is the original tex source code of tnhe manual that can be corrected: https://github.com/geotopmodel/geotop/tree/master/doc/manual  (doc/manual directory of thee master)

**Comment by ssenoner** [comment]
@yakopuz what do you say about this issue? 
I did a pull request to address this issue, you can see the results here:
[updated manual](https://github.com/geotopmodel/geotop/blob/5ae278199583f180594965757582b8a721d31bb6/doc/manual/users_man.pdf)

**Comment by yakopuz** [comment]
Thanks Samuel.
The manual is to update to the last code version,
However In red my suggestions

Keyword                 Description                                           M. U.      range                    Default Value
LSAI                       Leaf and Stem Area Index [L2=L2]    -               0, 10                      1
                                                                                Description                                                                                           range                     Default Value
SurFlowResExp (): Exponent of the law … with 0.5 is the Chezy law, with 0.67 the Manning law                       0.25 -0.85              0.67

**Comment by ssenoner** [comment]
@yakopuz sorry, can't see no red, can you please specify better?

**Comment by yakopuz** [comment]
Simply I suggest:

LSAI       Leaf and Stem Area Index  Range 0, 10           Default:           1

SurFlowResExp  Range 0.25 -0.85              Default:           0.67


with 0.5 is the Chezy law, with 0.67 the Manning law

Giacomo
